### ISSUE TITLE
Broken links in CSS

### ISSUE THREAD

**Issue by vladistan** [CommerceDataService/patent-process-and-search#104]
I see a lot of these in web log

open() "/home/ubuntu/uspto_ptab/searchtool/bower_components/designpatterns/generated/styles/select2.png" failed (2: No such file or directory), client: 151.207.250.51, server: localhost, request: "GET /bower_components/designpatterns/generated/styles/select2.png HTTP/1.1", host: "bdr-sit.etc.uspto.gov", referrer: "http://bdr-sit.etc.uspto.gov/bower_components/designpatterns/generated/styles/vendor.css"

Looks like select2.png got dropped somehow.. can you check what's wrong

**Comment by neka-io** [comment]
I see this too. It's a dependency of the [USPTO UI Design Library](https://github.com/USPTO/designpatterns) and the error is being generated from there. It's not in our code.  I've been meaning to create an issue on their repo.
