### ISSUE TITLE
Looks like some queries can still crash the site

### ISSUE THREAD

**Issue by vladistan** [CommerceDataService/patent-process-and-search#112]
Here is the crash log

appserver_1  | http://10.201.19.197:8983/solr/oadata_3_shard1_replica3/select?q={!q.op=AND df=textdata}"35 U.S.C. 102_" &fq=type:oa&wt=json&indent=true&rows=20&start=100&
hl=true&hl.snippets=10&hl.fl=textdata&hl.fragsize=200&hl.simple.pre=<code>&hl.simple.post=</code>&hl.usePhraseHighlighter=true&q.op=AND
web_1        | 151.207.250.51 - - [19/Jul/2016:10:55:41 +0000] "GET /newsearch?q=%2235%20U.S.C.%20102_%22%20&dataset=oa&fromdate=&todate=&art_unit=&documentcode=&pageno=6
 HTTP/1.1" 200 33120 "http://bdr-sit.etc.uspto.gov/newsearch?q=%2235%20U.S.C.%20102*%22%20&dataset=oa&fromdate=&todate=&art_unit=&documentcode=&pageno=5" "Mozilla/5.0 (Wi
ndows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" "-"
appserver_1  | http://10.201.19.197:8983/solr/oadata_3_shard1_replica3/select?q={!q.op=AND df=textdata}"35 U.S.C. 102b" &fq=type:oa&wt=json&indent=true&rows=20&start=0&hl
=true&hl.snippets=10&hl.fl=textdata&hl.fragsize=200&hl.simple.pre=<code>&hl.simple.post=</code>&hl.usePhraseHighlighter=true&q.op=AND
web_1        | 151.207.250.51 - - [19/Jul/2016:10:56:20 +0000] "GET /newsearch?q=%2235+U.S.C.+102b%22+&dataset=oa HTTP/1.1" 200 16009 "http://bdr-sit.etc.uspto.gov/newsea
rch?q=%2235%20U.S.C.%20102_%22%20&dataset=oa&fromdate=&todate=&art_unit=&documentcode=&pageno=6" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Geck
o) Chrome/43.0.2357.130 Safari/537.36" "-"
appserver_1  | http://10.201.19.197:8983/solr/oadata_3_shard1_replica3/select?q={!q.op=AND df=textdata}"35 U.S.C. 102_"  AND APPID:13383908&fq=type:oa&wt=json&indent=true
&rows=20&start=0&hl=true&hl.snippets=10&hl.fl=textdata&hl.fragsize=200&hl.simple.pre=<code>&hl.simple.post=</code>&hl.usePhraseHighlighter=true&q.op=AND
appserver_1  | /server/boot/search.js:91
appserver_1  |             if (body && typeof body.response.docs !== 'undefined') {
appserver_1  |                                             ^
appserver_1  |
appserver_1  | TypeError: Cannot read property 'docs' of undefined
appserver_1  |     at /server/boot/search.js:91:45
appserver_1  |     at Request.handleRequestResponse [as _callback](/node_modules/unirest/index.js:461:25)
appserver_1  |     at Request.self.callback (/node_modules/unirest/node_modules/request/request.js:373:22)
appserver_1  |     at emitTwo (events.js:106:13)
appserver_1  |     at Request.emit (events.js:191:7)
appserver_1  |     at Request.<anonymous> (/node_modules/unirest/node_modules/request/request.js:1318:14)
appserver_1  |     at emitOne (events.js:101:20)
appserver_1  |     at Request.emit (events.js:188:7)
appserver_1  |     at IncomingMessage.<anonymous> (/node_modules/unirest/node_modules/request/request.js:1266:12)
appserver_1  |     at emitNone (events.js:91:20)
web_1        | 2016/07/19 10:56:50 [error] 5#5: _59 upstream prematurely closed connection while reading response header from upstream, client: 151.207.250.51, server: lo
calhost, request: "GET /newsearch?q=%2235+U.S.C.+102_%22++AND+APPID%3A13383908&dataset=oa HTTP/1.1", upstream: "http://172.18.0.3:3000/newsearch?q=%2235+U.S.C.+102*%22++A
ND+APPID%3A13383908&dataset=oa", host: "bdr-sit.etc.uspto.gov", referrer: "http://bdr-sit.etc.uspto.gov/newsearch?q=%2235+U.S.C.+102b%22+&dataset=oa"
web_1        | 2016/07/19 10:56:50 [error] 5#5: _59 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 151.207.250.51, ser
ver: localhost, request: "GET /newsearch?q=%2235+U.S.C.+102_%22++AND+APPID%3A13383908&dataset=oa HTTP/1.1", upstream: "http://172.18.0.3:3000/media/50x.html", host: "bdr-
sit.etc.uspto.gov", referrer: "http://bdr-sit.etc.uspto.gov/newsearch?q=%2235+U.S.C.+102b%22+&dataset=oa"
web_1        | 151.207.250.51 - - [19/Jul/2016:10:56:50 +0000] "GET /newsearch?q=%2235+U.S.C.+102*%22++AND+APPID%3A13383908&dataset=oa HTTP/1.1" 502 575 "http://bdr-sit.e
tc.uspto.gov/newsearch?q=%2235+U.S.C.+102b%22+&dataset=oa" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
 "-"
appserver_1  |
appserver_1  | npm info lifecycle officeactions@1.0.1~start: Failed to exec start script
appserver_1  | npm ERR! Linux 4.4.11-23.53.amzn1.x86_64
appserver_1  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
appserver_1  | npm ERR! node v6.3.0
appserver_1  | npm ERR! npm  v3.10.3
appserver_1  | npm ERR! code ELIFECYCLE
appserver_1  | npm ERR! officeactions@1.0.1 start: `node .`
appserver_1  | npm ERR! Exit status 1
appserver_1  | npm ERR!
appserver_1  | npm ERR! Failed at the officeactions@1.0.1 start script 'node .'.
appserver_1  | npm ERR! Make sure you have the latest version of node.js and npm installed.
appserver_1  | npm ERR! If you do, this is most likely a problem with the officeactions package,
appserver_1  | npm ERR! not with npm itself.
appserver_1  | npm ERR! Tell the author that this fails on your system:
appserver_1  | npm ERR!     node .
appserver_1  | npm ERR! You can get information on how to open an issue for this project with:
appserver_1  | npm ERR!     npm bugs officeactions
appserver_1  | npm ERR! Or if that isn't available, you can get their info via:
appserver_1  | npm ERR!     npm owner ls officeactions
appserver_1  | npm ERR! There is likely additional logging output above.

**Comment by vladistan** [comment]
Just crashed again... here is another error dump.  It's the same as previous one

appserver_1  | http://10.201.19.197:8983/solr/oadata_3_shard1_replica3/select?q={!q.op=AND df=textdata}"judicial exception" OR "abstract idea" OR "natural phenomena" OR "
natural phenomenon" OR "natural product" OR "law of nature" OR "product of nature" &fq=type:oa&wt=json&indent=true&rows=20&start=0&hl=true&hl.snippets=10&hl.fl=textdata&h
l.fragsize=200&hl.simple.pre=<code>&hl.simple.post=</code>&hl.usePhraseHighlighter=true&q.op=AND
web_1        | 151.207.250.61 - - [19/Jul/2016:17:52:56 +0000] "GET /newsearch?q=%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+
phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22+&dataset=oa HTTP/1.1" 200 67044 "http://bdr-sit.etc.uspto.gov/newsearch?q=%28%221
01%22+AND+%22Subject+Matter%22%29+NOT+%22double+patenting%22&dataset=oa" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130
Safari/537.36" "-"
appserver_1  | http://10.201.19.197:8983/solr/oadata_3_shard1_replica3/select?q={!q.op=AND df=textdata}(("judicial exception" OR "abstract idea" OR "natural phenomena" OR
 "natural phenomenon" OR "natural product" OR "law of nature" OR "product of nature") AND ("101 AND "Subject Matter"))&fq=type:oa&wt=json&indent=true&rows=20&start=0&hl=t
rue&hl.snippets=10&hl.fl=textdata&hl.fragsize=200&hl.simple.pre=<code>&hl.simple.post=</code>&hl.usePhraseHighlighter=true&q.op=AND
appserver_1  | /server/boot/search.js:91
appserver_1  |             if (body && typeof body.response.docs !== 'undefined') {
appserver_1  |                                             ^
appserver_1  |
appserver_1  | TypeError: Cannot read property 'docs' of undefined
appserver_1  |     at /server/boot/search.js:91:45
appserver_1  |     at Request.handleRequestResponse [as _callback](/node_modules/unirest/index.js:461:25)
appserver_1  |     at Request.self.callback (/node_modules/unirest/node_modules/request/request.js:373:22)
appserver_1  |     at emitTwo (events.js:106:13)
appserver_1  |     at Request.emit (events.js:191:7)
appserver_1  |     at Request.<anonymous> (/node_modules/unirest/node_modules/request/request.js:1318:14)
appserver_1  |     at emitOne (events.js:101:20)
appserver_1  |     at Request.emit (events.js:188:7)
appserver_1  |     at IncomingMessage.<anonymous> (/node_modules/unirest/node_modules/request/request.js:1266:12)
appserver_1  |     at emitNone (events.js:91:20)
appserver_1  |     at IncomingMessage.emit (events.js:185:7)
web_1        | 2016/07/19 17:56:18 [error] 5#5: *214 upstream prematurely closed connection while reading response header from upstream, client: 151.207.250.61, server: localhost, request: "GET /newsearch?q=%28%28%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22%29+AND+%28%22101+AND+%22Subject+Matter%22%29%29&dataset=oa HTTP/1.1", upstream: "http://172.18.0.3:3000/newsearch?q=%28%28%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22%29+AND+%28%22101+AND+%22Subject+Matter%22%29%29&dataset=oa", host: "bdr-sit.etc.uspto.gov", referrer: "http://bdr-sit.etc.uspto.gov/newsearch?q=%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22+&dataset=oa"
web_1        | 2016/07/19 17:56:18 [error] 5#5: *214 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 151.207.250.61, server: localhost, request: "GET /newsearch?q=%28%28%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22%29+AND+%28%22101+AND+%22Subject+Matter%22%29%29&dataset=oa HTTP/1.1", upstream: "http://172.18.0.3:3000/media/50x.html", host: "bdr-sit.etc.uspto.gov", referrer: "http://bdr-sit.etc.uspto.gov/newsearch?q=%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22+&dataset=oa"
web_1        | 151.207.250.61 - - [19/Jul/2016:17:56:18 +0000] "GET /newsearch?q=%28%28%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22%29+AND+%28%22101+AND+%22Subject+Matter%22%29%29&dataset=oa HTTP/1.1" 502 575 "http://bdr-sit.etc.uspto.gov/newsearch?q=%22judicial+exception%22+OR+%22abstract+idea%22+OR+%22natural+phenomena%22+OR+%22natural+phenomenon%22+OR+%22natural+product%22+OR+%22law+of+nature%22+OR+%22product+of+nature%22+&dataset=oa" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" "-"
appserver_1  |

**Comment by vladistan** [comment]
@bahadasx @noonkay can you look into this?

**Comment by neka-io** [comment]
I'm looking into this and other error handling. Originally this is what I planned to get done this afternoon but got side tracked by user authentication requests
